//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceAsync.ServiceReferenceVentas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentRpta", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentRpta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DocTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RegisteredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocEntry {
            get {
                return this.DocEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.DocEntryField, value) != true)) {
                    this.DocEntryField = value;
                    this.RaisePropertyChanged("DocEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DocTotal {
            get {
                return this.DocTotalField;
            }
            set {
                if ((this.DocTotalField.Equals(value) != true)) {
                    this.DocTotalField = value;
                    this.RaisePropertyChanged("DocTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Registered {
            get {
                return this.RegisteredField;
            }
            set {
                if ((this.RegisteredField.Equals(value) != true)) {
                    this.RegisteredField = value;
                    this.RaisePropertyChanged("Registered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentRptaBD", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentRptaBD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Proceso {
            get {
                return this.ProcesoField;
            }
            set {
                if ((this.ProcesoField.Equals(value) != true)) {
                    this.ProcesoField = value;
                    this.RaisePropertyChanged("Proceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string almacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoTiendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocrCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocrCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocrCode4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ocrCode5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tiempoFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tiempoSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioSAPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activo {
            get {
                return this.activoField;
            }
            set {
                if ((object.ReferenceEquals(this.activoField, value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string almacen {
            get {
                return this.almacenField;
            }
            set {
                if ((object.ReferenceEquals(this.almacenField, value) != true)) {
                    this.almacenField = value;
                    this.RaisePropertyChanged("almacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoTienda {
            get {
                return this.codigoTiendaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoTiendaField, value) != true)) {
                    this.codigoTiendaField = value;
                    this.RaisePropertyChanged("codigoTienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseniaSAP {
            get {
                return this.contraseniaSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaSAPField, value) != true)) {
                    this.contraseniaSAPField = value;
                    this.RaisePropertyChanged("contraseniaSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocrCode {
            get {
                return this.ocrCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ocrCodeField, value) != true)) {
                    this.ocrCodeField = value;
                    this.RaisePropertyChanged("ocrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocrCode2 {
            get {
                return this.ocrCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ocrCode2Field, value) != true)) {
                    this.ocrCode2Field = value;
                    this.RaisePropertyChanged("ocrCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocrCode3 {
            get {
                return this.ocrCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ocrCode3Field, value) != true)) {
                    this.ocrCode3Field = value;
                    this.RaisePropertyChanged("ocrCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocrCode4 {
            get {
                return this.ocrCode4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ocrCode4Field, value) != true)) {
                    this.ocrCode4Field = value;
                    this.RaisePropertyChanged("ocrCode4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ocrCode5 {
            get {
                return this.ocrCode5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ocrCode5Field, value) != true)) {
                    this.ocrCode5Field = value;
                    this.RaisePropertyChanged("ocrCode5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tiempoFactura {
            get {
                return this.tiempoFacturaField;
            }
            set {
                if ((this.tiempoFacturaField.Equals(value) != true)) {
                    this.tiempoFacturaField = value;
                    this.RaisePropertyChanged("tiempoFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tiempoSalida {
            get {
                return this.tiempoSalidaField;
            }
            set {
                if ((this.tiempoSalidaField.Equals(value) != true)) {
                    this.tiempoSalidaField = value;
                    this.RaisePropertyChanged("tiempoSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuarioSAP {
            get {
                return this.usuarioSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioSAPField, value) != true)) {
                    this.usuarioSAPField = value;
                    this.RaisePropertyChanged("usuarioSAP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockProducto", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class StockProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhsCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UM {
            get {
                return this.UMField;
            }
            set {
                if ((object.ReferenceEquals(this.UMField, value) != true)) {
                    this.UMField = value;
                    this.RaisePropertyChanged("UM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhsCode {
            get {
                return this.WhsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhsCodeField, value) != true)) {
                    this.WhsCodeField = value;
                    this.RaisePropertyChanged("WhsCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lote", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceVentas.Models")]
    [System.SerializableAttribute()]
    public partial class Lote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaEmisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhsCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNum {
            get {
                return this.BatchNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNumField, value) != true)) {
                    this.BatchNumField = value;
                    this.RaisePropertyChanged("BatchNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaEmision {
            get {
                return this.FechaEmisionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaEmisionField, value) != true)) {
                    this.FechaEmisionField = value;
                    this.RaisePropertyChanged("FechaEmision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WhsCode {
            get {
                return this.WhsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WhsCodeField, value) != true)) {
                    this.WhsCodeField = value;
                    this.RaisePropertyChanged("WhsCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVentas.IServiceVentas")]
    public interface IServiceVentas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/Login", ReplyAction="http://tempuri.org/IServiceVentas/LoginResponse")]
        string Login();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/Login", ReplyAction="http://tempuri.org/IServiceVentas/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createDelivery", ReplyAction="http://tempuri.org/IServiceVentas/createDeliveryResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createDelivery(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createDelivery", ReplyAction="http://tempuri.org/IServiceVentas/createDeliveryResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createDeliveryAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createInvoice", ReplyAction="http://tempuri.org/IServiceVentas/createInvoiceResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createInvoice(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createInvoice", ReplyAction="http://tempuri.org/IServiceVentas/createInvoiceResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createInvoiceAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createPayment", ReplyAction="http://tempuri.org/IServiceVentas/createPaymentResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createPayment(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createPayment", ReplyAction="http://tempuri.org/IServiceVentas/createPaymentResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createPaymentAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createCreditNote", ReplyAction="http://tempuri.org/IServiceVentas/createCreditNoteResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createCreditNote(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createCreditNote", ReplyAction="http://tempuri.org/IServiceVentas/createCreditNoteResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createCreditNoteAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createItem", ReplyAction="http://tempuri.org/IServiceVentas/createItemResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createItem(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createItem", ReplyAction="http://tempuri.org/IServiceVentas/createItemResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createItemAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createEntrada", ReplyAction="http://tempuri.org/IServiceVentas/createEntradaResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createEntrada(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createEntrada", ReplyAction="http://tempuri.org/IServiceVentas/createEntradaResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createEntradaAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/updateItem", ReplyAction="http://tempuri.org/IServiceVentas/updateItemResponse")]
        bool updateItem(string obj, string document, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/updateItem", ReplyAction="http://tempuri.org/IServiceVentas/updateItemResponse")]
        System.Threading.Tasks.Task<bool> updateItemAsync(string obj, string document, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/ExistItem", ReplyAction="http://tempuri.org/IServiceVentas/ExistItemResponse")]
        bool ExistItem(string ItemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/ExistItem", ReplyAction="http://tempuri.org/IServiceVentas/ExistItemResponse")]
        System.Threading.Tasks.Task<bool> ExistItemAsync(string ItemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/ExistSN", ReplyAction="http://tempuri.org/IServiceVentas/ExistSNResponse")]
        bool ExistSN(string CardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/ExistSN", ReplyAction="http://tempuri.org/IServiceVentas/ExistSNResponse")]
        System.Threading.Tasks.Task<bool> ExistSNAsync(string CardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createBusinessPartner", ReplyAction="http://tempuri.org/IServiceVentas/createBusinessPartnerResponse")]
        bool createBusinessPartner(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/createBusinessPartner", ReplyAction="http://tempuri.org/IServiceVentas/createBusinessPartnerResponse")]
        System.Threading.Tasks.Task<bool> createBusinessPartnerAsync(string obj, string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerDocumentDB", ReplyAction="http://tempuri.org/IServiceVentas/registerDocumentDBResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.DocumentRptaBD registerDocumentDB(string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerDocumentDB", ReplyAction="http://tempuri.org/IServiceVentas/registerDocumentDBResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRptaBD> registerDocumentDBAsync(string document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerDocumentDBDetail", ReplyAction="http://tempuri.org/IServiceVentas/registerDocumentDBDetailResponse")]
        bool registerDocumentDBDetail(string documentDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerDocumentDBDetail", ReplyAction="http://tempuri.org/IServiceVentas/registerDocumentDBDetailResponse")]
        System.Threading.Tasks.Task<bool> registerDocumentDBDetailAsync(string documentDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentDBResponse")]
        int registerPaymentDB(string payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentDBResponse")]
        System.Threading.Tasks.Task<int> registerPaymentDBAsync(string payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentInvDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentInvDBResponse")]
        bool registerPaymentInvDB(string paymentInv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentInvDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentInvDBResponse")]
        System.Threading.Tasks.Task<bool> registerPaymentInvDBAsync(string paymentInv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentCashDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentCashDBResponse")]
        bool registerPaymentCashDB(string paymentCash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/registerPaymentCashDB", ReplyAction="http://tempuri.org/IServiceVentas/registerPaymentCashDBResponse")]
        System.Threading.Tasks.Task<bool> registerPaymentCashDBAsync(string paymentCash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getTiendaInfoDB", ReplyAction="http://tempuri.org/IServiceVentas/getTiendaInfoDBResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.Store getTiendaInfoDB(string codigoTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getTiendaInfoDB", ReplyAction="http://tempuri.org/IServiceVentas/getTiendaInfoDBResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Store> getTiendaInfoDBAsync(string codigoTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStockStore", ReplyAction="http://tempuri.org/IServiceVentas/getStockStoreResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStockStore(string whsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStockStore", ReplyAction="http://tempuri.org/IServiceVentas/getStockStoreResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStockStoreAsync(string whsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStockStoreReserva", ReplyAction="http://tempuri.org/IServiceVentas/getStockStoreReservaResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStockStoreReserva(string whsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStockStoreReserva", ReplyAction="http://tempuri.org/IServiceVentas/getStockStoreReservaResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStockStoreReservaAsync(string whsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStocktStoreItem", ReplyAction="http://tempuri.org/IServiceVentas/getStocktStoreItemResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStocktStoreItem(string whsCode, string itemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getStocktStoreItem", ReplyAction="http://tempuri.org/IServiceVentas/getStocktStoreItemResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStocktStoreItemAsync(string whsCode, string itemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getItem", ReplyAction="http://tempuri.org/IServiceVentas/getItemResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.Item[] getItem(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getItem", ReplyAction="http://tempuri.org/IServiceVentas/getItemResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Item[]> getItemAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getLote", ReplyAction="http://tempuri.org/IServiceVentas/getLoteResponse")]
        WindowsServiceAsync.ServiceReferenceVentas.Lote[] getLote(string itemCode, string whsCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceVentas/getLote", ReplyAction="http://tempuri.org/IServiceVentas/getLoteResponse")]
        System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Lote[]> getLoteAsync(string itemCode, string whsCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceVentasChannel : WindowsServiceAsync.ServiceReferenceVentas.IServiceVentas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceVentasClient : System.ServiceModel.ClientBase<WindowsServiceAsync.ServiceReferenceVentas.IServiceVentas>, WindowsServiceAsync.ServiceReferenceVentas.IServiceVentas {
        
        public ServiceVentasClient() {
        }
        
        public ServiceVentasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceVentasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceVentasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login() {
            return base.Channel.Login();
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync() {
            return base.Channel.LoginAsync();
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createDelivery(string obj, string document) {
            return base.Channel.createDelivery(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createDeliveryAsync(string obj, string document) {
            return base.Channel.createDeliveryAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createInvoice(string obj, string document) {
            return base.Channel.createInvoice(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createInvoiceAsync(string obj, string document) {
            return base.Channel.createInvoiceAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createPayment(string obj, string document) {
            return base.Channel.createPayment(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createPaymentAsync(string obj, string document) {
            return base.Channel.createPaymentAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createCreditNote(string obj, string document) {
            return base.Channel.createCreditNote(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createCreditNoteAsync(string obj, string document) {
            return base.Channel.createCreditNoteAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createItem(string obj, string document) {
            return base.Channel.createItem(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createItemAsync(string obj, string document) {
            return base.Channel.createItemAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta createEntrada(string obj, string document) {
            return base.Channel.createEntrada(obj, document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRpta> createEntradaAsync(string obj, string document) {
            return base.Channel.createEntradaAsync(obj, document);
        }
        
        public bool updateItem(string obj, string document, string id) {
            return base.Channel.updateItem(obj, document, id);
        }
        
        public System.Threading.Tasks.Task<bool> updateItemAsync(string obj, string document, string id) {
            return base.Channel.updateItemAsync(obj, document, id);
        }
        
        public bool ExistItem(string ItemCode) {
            return base.Channel.ExistItem(ItemCode);
        }
        
        public System.Threading.Tasks.Task<bool> ExistItemAsync(string ItemCode) {
            return base.Channel.ExistItemAsync(ItemCode);
        }
        
        public bool ExistSN(string CardCode) {
            return base.Channel.ExistSN(CardCode);
        }
        
        public System.Threading.Tasks.Task<bool> ExistSNAsync(string CardCode) {
            return base.Channel.ExistSNAsync(CardCode);
        }
        
        public bool createBusinessPartner(string obj, string document) {
            return base.Channel.createBusinessPartner(obj, document);
        }
        
        public System.Threading.Tasks.Task<bool> createBusinessPartnerAsync(string obj, string document) {
            return base.Channel.createBusinessPartnerAsync(obj, document);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.DocumentRptaBD registerDocumentDB(string document) {
            return base.Channel.registerDocumentDB(document);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.DocumentRptaBD> registerDocumentDBAsync(string document) {
            return base.Channel.registerDocumentDBAsync(document);
        }
        
        public bool registerDocumentDBDetail(string documentDetail) {
            return base.Channel.registerDocumentDBDetail(documentDetail);
        }
        
        public System.Threading.Tasks.Task<bool> registerDocumentDBDetailAsync(string documentDetail) {
            return base.Channel.registerDocumentDBDetailAsync(documentDetail);
        }
        
        public int registerPaymentDB(string payment) {
            return base.Channel.registerPaymentDB(payment);
        }
        
        public System.Threading.Tasks.Task<int> registerPaymentDBAsync(string payment) {
            return base.Channel.registerPaymentDBAsync(payment);
        }
        
        public bool registerPaymentInvDB(string paymentInv) {
            return base.Channel.registerPaymentInvDB(paymentInv);
        }
        
        public System.Threading.Tasks.Task<bool> registerPaymentInvDBAsync(string paymentInv) {
            return base.Channel.registerPaymentInvDBAsync(paymentInv);
        }
        
        public bool registerPaymentCashDB(string paymentCash) {
            return base.Channel.registerPaymentCashDB(paymentCash);
        }
        
        public System.Threading.Tasks.Task<bool> registerPaymentCashDBAsync(string paymentCash) {
            return base.Channel.registerPaymentCashDBAsync(paymentCash);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.Store getTiendaInfoDB(string codigoTienda) {
            return base.Channel.getTiendaInfoDB(codigoTienda);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Store> getTiendaInfoDBAsync(string codigoTienda) {
            return base.Channel.getTiendaInfoDBAsync(codigoTienda);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStockStore(string whsCode) {
            return base.Channel.getStockStore(whsCode);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStockStoreAsync(string whsCode) {
            return base.Channel.getStockStoreAsync(whsCode);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStockStoreReserva(string whsCode) {
            return base.Channel.getStockStoreReserva(whsCode);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStockStoreReservaAsync(string whsCode) {
            return base.Channel.getStockStoreReservaAsync(whsCode);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.StockProducto[] getStocktStoreItem(string whsCode, string itemCode) {
            return base.Channel.getStocktStoreItem(whsCode, itemCode);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.StockProducto[]> getStocktStoreItemAsync(string whsCode, string itemCode) {
            return base.Channel.getStocktStoreItemAsync(whsCode, itemCode);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.Item[] getItem(string code) {
            return base.Channel.getItem(code);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Item[]> getItemAsync(string code) {
            return base.Channel.getItemAsync(code);
        }
        
        public WindowsServiceAsync.ServiceReferenceVentas.Lote[] getLote(string itemCode, string whsCode) {
            return base.Channel.getLote(itemCode, whsCode);
        }
        
        public System.Threading.Tasks.Task<WindowsServiceAsync.ServiceReferenceVentas.Lote[]> getLoteAsync(string itemCode, string whsCode) {
            return base.Channel.getLoteAsync(itemCode, whsCode);
        }
    }
}
